### ISSUE TITLE
副本刷本何时更新

### ISSUE THREAD

**Issue by chenshoyuan** [pcrbot/erinilis-modules#106]
最新的华馆和海染圣遗物何时更新

**Comment by chenchenriver** [comment]
d

**Comment by yuyumoko** [comment]
??

**Comment by chenshoyuan** [comment]
最新的圣遗物本何时群里能模拟刷取




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月17日(星期五) 晚上11:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [pcrbot/erinilis-modules] 副本刷本何时更新 (Issue #106)





 
??
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yuyumoko** [comment]
是 什么功能?

**Comment by chenshoyuan** [comment]
这两套圣遗物何时更新
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pcrbot/erinilis-modules"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月17日(星期五) 晚上11:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pcrbot/erinilis-modules] 副本刷本何时更新 (Issue #106)





 
是 什么功能?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chenshoyuan** [comment]
![image](https://user-images.githubusercontent.com/94736026/146569326-7470635e-168b-40bb-9e64-f5d6a99ff932.png)

**Comment by chenshoyuan** [comment]
![image](https://user-images.githubusercontent.com/94736026/146569396-6bf744b3-407f-430b-b739-83d7db7ada2a.png)

**Comment by yuyumoko** [comment]
我有什么插件用到这个吗?
