### ISSUE TITLE
新的文件更新后还是报错

### ISSUE THREAD

**Issue by 1055169799** [pcrbot/erinilis-modules#110]
机器人回复为 JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

**Comment by yuyumoko** [comment]
现在米游社ban了腾讯云和阿里云服务器 目前我树莓派本地网络可以

**Comment by 1055169799** [comment]
> 
好的，了解了

**Comment by NepPure** [comment]
我嘞个去

**Comment by wudifeixue** [comment]
这个问题也可以看看这边讨论
https://github.com/Arondight/Adachi-BOT/issues/522#issuecomment-1000749048

**Comment by ryousora** [comment]
实测把
> egenshin/player_info/query.py

里面的`https://api-takumi.mihoyo.com/`替换成`https://api-takumi-record.mihoyo.com/`就能正常使用了

**Comment by 1055169799** [comment]
> 这个问题也可以看看这边讨论 [Arondight/Adachi-BOT#522 (comment)](https://github.com/Arondight/Adachi-BOT/issues/522#issuecomment-1000749048)

嗯嗯，确实是云服务器的IP被ban，昨晚试了一晚上，想从我本地电脑映射端口转发给服务器，但是技术有限，没成功（为什么不挂本地原因是我电脑是公司工作机，另外虽然24小时开机，但是偶尔会有手动关机重启的可能）

**Comment by Mark9804** [comment]
> > 这个问题也可以看看这边讨论 [Arondight/Adachi-BOT#522 (comment)](https://github.com/Arondight/Adachi-BOT/issues/522#issuecomment-1000749048)
> 
> 嗯嗯，确实是云服务器的IP被ban，昨晚试了一晚上，想从我本地电脑映射端口转发给服务器，但是技术有限，没成功（为什么不挂本地原因是我电脑是公司工作机，另外虽然24小时开机，但是偶尔会有手动关机重启的可能）

能告知一下你的 VPS 是哪家哪个机房的吗，我在收集数据猜测屏蔽的触发条件

**Comment by 1055169799** [comment]
> > > 这个问题也可以看看这边讨论 [Arondight/Adachi-BOT#522 (comment)](https://github.com/Arondight/Adachi-BOT/issues/522#issuecomment-1000749048)
> > 
> > 
> > 嗯嗯，确实是云服务器的IP被ban，昨晚试了一晚上，想从我本地电脑映射端口转发给服务器，但是技术有限，没成功（为什么不挂本地原因是我电脑是公司工作机，另外虽然24小时开机，但是偶尔会有手动关机重启的可能）
> 
> 能告知一下你的 VPS 是哪家哪个机房的吗，我在收集数据猜测屏蔽的触发条件

腾讯云的，上海
