### ISSUE TITLE
这个大佬的插件可以查米游社欸

### ISSUE THREAD

**Issue by 3273576540** [pcrbot/erinilis-modules#111]
实测hoshino和none2都可以
项目地址：https://github.com/KimigaiiWuyi/GenshinUID

**Comment by yuyumoko** [comment]
没必要 大部分只需要查游戏UID即可

**Comment by 3273576540** [comment]
我也觉得，可以截取部分试试嘛

**Comment by yuyumoko** [comment]
啊? 啥部分

**Comment by 3273576540** [comment]
就是爬米游社的方式吧，我不懂这个，弱弱的问问。不是api用不了了嘛，但这个插件却能查，腾讯云。

**Comment by yuyumoko** [comment]
我问了作者了 他说现在不行了 下午短暂可以了半小时

**Comment by 3273576540** [comment]
啊，现在都行欸，我还以为一直都行，那没事了。

**Comment by yuyumoko** [comment]
那可能是部分人吧

**Comment by 3273576540** [comment]
好的，谢谢大佬耐心解答！晚安！
