### ISSUE TITLE
猜语音插件出bug了吗

### ISSUE THREAD

**Issue by 3273576540** [pcrbot/erinilis-modules#113]
一直这样
![image](https://user-images.githubusercontent.com/94744908/147766794-abdd14ce-bd46-44a8-a456-dc6ae606350d.png)

**Comment by 3273576540** [comment]
作者大大，好像真的出bug了

**Comment by yuyumoko** [comment]
你在群内说一句`更新原神语音资源`可破

**Comment by 3273576540** [comment]
还是不行

**Comment by 3273576540** [comment]
日韩英 困难都行
唯独中文不行，更新资源还是重装都不行
默认就是中文，所以一发指令就响应很久才报错
因为不只是我一个的问题，我问了好几个bot主人，都报错
