### ISSUE TITLE
现在的QQ私聊会导致机器人封号，可否自己手动修改数据库里的cookie信息

### ISSUE THREAD

**Issue by 1055169799** [pcrbot/erinilis-modules#130]
现在的QQ私聊会导致机器人封号，可否自己手动修改数据库里的cookie信息，我用DB Browser for SQLite打开remind.sqlite，但是看不到任何cookie数据，请问该用什么可以打开修改。
![image](https://user-images.githubusercontent.com/41286675/154414976-0573f91d-1eaa-4dce-ac2c-2cd66ffc30bb.png)

或者设置一下让机器人不要立刻返回数据，似乎秒回就会封号，不秒回还不知道会不会封号，多次冻结都封7天了，不私聊又绑定不上cookie。

**Comment by chingkingm** [comment]
1. cookie信息在uid.sqlite->unnamed里
2. 会封号的是向非好友发送临时会话，不是私聊。可以在设置->消息通知->临时会话设置中关掉临时会话，要求加好友后才能绑定，单向好友也行

**Comment by 1055169799** [comment]
> 1. cookie信息在uid.sqlite->unnamed里
> 2. 会封号的是向非好友发送临时会话，不是私聊。可以在设置->消息通知->临时会话设置中关掉临时会话，要求加好友后才能绑定，单向好友也行

好的，我试试

**Comment by 1055169799** [comment]
> 1. uid.sqlite

修改成功了，谢谢

**Comment by 1055169799** [comment]
> 1. cookie信息在uid.sqlite->unnamed里
> 2. 会封号的是向非好友发送临时会话，不是私聊。可以在设置->消息通知->临时会话设置中关掉临时会话，要求加好友后才能绑定，单向好友也行
