### ISSUE TITLE
eqa关闭"SU为所有群问答"后出错

### ISSUE THREAD

**Issue by shirleygrey** [pcrbot/erinilis-modules#15]
现象：super_admin_is_all_group: false后所有问答无回复
async def answer(ctx):
    ......
    # 获取到当前群的列表 判断是否来自该群 或者是否是超级管理员
    # 超级管理员设置的是否为所有群问答
    ans_list = util.filter_list(ans_list, lambda x: group_id == x['group_id'] or (
            x['user_id'] in admins) if super_admin_is_all_group else False)
若super_admin_is_all_group设置为false则 ans_list 返回[]

**Comment by yuyumoko** [comment]
我测试的没问题 这个是在那个群设置的那个群就能回答

**Comment by shirleygrey** [comment]
草 原来这个就是我提的问题
当时我自行解决的做法是：
修改为    
ans_list = util.filter_list(ans_list, lambda x: group_id == x['group_id'] or ((
            x['user_id'] in admins) if super_admin_is_all_group else False))
