### ISSUE TITLE
貌似是转码问题

### ISSUE THREAD

**Issue by damemod** [pcrbot/erinilis-modules#16]
![image](https://user-images.githubusercontent.com/85817502/124468820-1f47f680-dd89-11eb-8471-677098f7066a.png)

**Comment by yuyumoko** [comment]
怎么触发的呢

**Comment by damemod** [comment]
总体来说，确实有明显问题。但是我不知道。反应特征是不回复，后台日志入手

**Comment by damemod** [comment]
很抱歉没有说清楚

**Comment by yuyumoko** [comment]
来 你加我一下 389897773
