### ISSUE TITLE
查询uid和抽卡可以考虑加个冷却

### ISSUE THREAD

**Issue by NepPure** [pcrbot/erinilis-modules#29]
毕竟一个账号限制30次，不限制一个人一会就刷完了 

）捂脸

**Comment by yuyumoko** [comment]
你可以多申请几个账号 比如我有5个 就150次,

**Comment by NepPure** [comment]
米游社可以只用邮箱注册吗

**Comment by yuyumoko** [comment]
你要觉得麻烦可以去某宝整几个自抽号 一样的

**Comment by yuyumoko** [comment]
重复查一个人 不会计算限额的  而且界面是有缓存的

**Comment by NepPure** [comment]
> 你要觉得麻烦可以去某宝整几个自抽号 一样的

太有道理了谢谢大佬
