### ISSUE TITLE
大家问【图片】时只有设置该问题的人才能触发该问题

### ISSUE THREAD

**Issue by Cappuccilo** [pcrbot/erinilis-modules#3]
后台查看CQ码发现[CQ:image,file=b5ef9af2e542dceec0b5bf80bc48c882.image,url=http://gchat.qpic.cn/gchatpic_new/_**7xxxxxxx**_/835788211-2663112555-B5EF9AF2E542DCEEC0B5BF80BC48C882/0?term=2]
url中会附带发送图片的QQ号(加粗斜体部分)，其他相同，以至于只有设置该问题的人才能触发该问题

**Comment by yuyumoko** [comment]
因为设置时的图片和设置后的图片不一样(这里指md5)  可能是被压缩了  导致别人看到的和你自己的不一致.
解决方法 把对方发送的图片再设置一次.
