### ISSUE TITLE
原神卡池记录统计插件,需要怎么样使用啊

### ISSUE THREAD

**Issue by Levi233** [pcrbot/erinilis-modules#33]
我fork了网页,修改host了然后部署,开启pages,然后网页只有标题,内容什么都没有,还有其他什么步骤吗,能教一下吗

**Comment by yuyumoko** [comment]
我也不太清楚呀.. 也没啥步骤了

**Comment by Levi233** [comment]
![image](https://user-images.githubusercontent.com/21984877/129474122-278ce225-9769-4983-aaec-5d245e427950.png)
我部署了,开启Pages,网页就会没内容不知道怎么回事
https://levi233.github.io/genshin-gacha-analyzer/

**Comment by yuyumoko** [comment]
![image](https://user-images.githubusercontent.com/12822506/129474255-9f6eb7bd-ad75-4b8c-9a2d-620e0ed76635.png)
是这样吗

**Comment by Levi233** [comment]
![image](https://user-images.githubusercontent.com/21984877/129474411-ac847385-9e93-4ea6-b402-fdaef4c80cc7.png)

**Comment by Levi233** [comment]
是这样啊

**Comment by Levi233** [comment]
如果使用vercel,在部署的时候就会报错

**Comment by yuyumoko** [comment]
那我不知道了

**Comment by Levi233** [comment]
那看来我用不了了
