### ISSUE TITLE
埃洛伊的背景色应该是偏红色那种

### ISSUE THREAD

**Issue by NepPure** [pcrbot/erinilis-modules#42]
和其他角色都不一样

![image](https://user-images.githubusercontent.com/12379907/131936139-51cc31e3-0791-41f7-a6bf-906cca7ff9be.png)

要不要改一下

**Comment by yuyumoko** [comment]
啥意思,, 埃洛伊是5星啊..

**Comment by yuyumoko** [comment]
就4星和5星的背景区别

**Comment by NepPure** [comment]
稍等我截图给你看看，这个联动角色有特殊背景色

**Comment by yuyumoko** [comment]
@A-kirami 这个是明见佬pr给我的

**Comment by NepPure** [comment]
![image](https://user-images.githubusercontent.com/12379907/131936703-ef0aecba-5875-4e15-a23a-0ce45eb8068e.png)

![image](https://user-images.githubusercontent.com/12379907/131936716-09d0317a-bc1f-43e7-8cc1-1f97c6d7a6b7.png)


米游社

![image](https://user-images.githubusercontent.com/12379907/131936741-7c8d8a01-7db0-4de1-acc4-a09f926d3c05.png)

**Comment by yuyumoko** [comment]
建议直接来我群 这样方便找我修bug 723220342

**Comment by NepPure** [comment]
> 建议直接来我群 这样方便找我修bug 723220342

来了来了！！！
