### ISSUE TITLE
原神玩家信息

### ISSUE THREAD

**Issue by poriuk** [pcrbot/erinilis-modules#43]
之前添加cookies绑定玩家信息是正常的，现在输入ys#UID就显示UID不存在，希望能修复这个问题

**Comment by scofieldle** [comment]
米游社是不是加了什么反爬取的代码，目前的插件会返回invalid requests

**Comment by yuyumoko** [comment]
我不知道啊.. 这个只能等别人做出来了

**Comment by DaiShengSheng** [comment]
氵社更新反爬了，只能等一波了
