### ISSUE TITLE
关于原神信息的cookies

### ISSUE THREAD

**Issue by vaqua** [pcrbot/erinilis-modules#46]
大佬,请问config.yml里的cookies是要填字符串还是单纯一串数字字母?
![image](https://github.com/vaqua/img/blob/main/%E6%A0%BC%E5%BC%8F.png?raw=true)
```py
cookies:
    - account_id=15xxx; cookie_token=Omxxxx;
```

上面的格式,还是下面的格式?
```py
cookies:
    "account_id=15xxx; cookie_token=Omxxxx;"
```

**Comment by yuyumoko** [comment]
实际上只需要account_id和cookie_token  或者你也可以全填 没差别的

**Comment by yuyumoko** [comment]
是
cookies:
    - account_id=15xxx; cookie_token=Omxxxx;

**Comment by vaqua** [comment]
大佬,我已经按你的回复设置cookie了,然而ys#uid命令还是没反应,原神公告/收集材料的命令能执行,就是查询UID的命令没反应,请问哪里可以查看报错日志呢?

**Comment by yuyumoko** [comment]
一般有2个窗口,  都可以截图过来

**Comment by vaqua** [comment]
图1是HoshinoBot的输出:
![](https://github.com/vaqua/img/blob/main/01.png)
图2是go-cqhttp的输出:
![](https://github.com/vaqua/img/blob/main/02.png)
大佬能看到图片吗?

**Comment by yuyumoko** [comment]
不能

**Comment by vaqua** [comment]
大佬,我编辑了一下,图片可以看了

**Comment by yuyumoko** [comment]
`python3 -m pip install pixivpy -i https://pypi.tuna.tsinghua.edu.cn/simple`
`python3 -m pip install xlsxwriter -i https://pypi.tuna.tsinghua.edu.cn/simple`

你先..运行这2句

**Comment by vaqua** [comment]
![](https://github.com/vaqua/img/blob/main/03.png?raw=true)
大佬,我按照你的回复运行了,出现上面的情况

**Comment by yuyumoko** [comment]
不可以吗??

**Comment by vaqua** [comment]
查询UID信息,机器人没回应..
按照例子的命令:
ys#105293904 机器人没回应

**Comment by yuyumoko** [comment]
啊这 控制台啥报错都没有吗

**Comment by vaqua** [comment]
一点报错都没
![image](https://github.com/vaqua/img/blob/main/04.png?raw=true)
![image](https://github.com/vaqua/img/blob/main/05.png?raw=true)

**Comment by yuyumoko** [comment]
你都没加载成功...

**Comment by yuyumoko** [comment]
吧egenshin文件夹放到上一级目录 然后在bot的config里添加egenshin模块

**Comment by vaqua** [comment]
哇,我成功了!,谢谢大佬!
我之前以为在bot的config里添加erinilis-modules就能用下面的子模块了,原来是和普通模一样使用: 要放到上一级目录里再在config里添加子模块.
多谢大佬耐心教导我这个菜鸟!!!
