### ISSUE TITLE
抽卡加载问题

### ISSUE THREAD

**Issue by liuqianpan2008** [pcrbot/erinilis-modules#47]
![QQ截图20210910180211](https://user-images.githubusercontent.com/80571808/132838931-7d792e53-a91b-48b5-ae99-8f6535583773.png)

**Comment by yuyumoko** [comment]
我猜你有2个抽卡插件,, 你可以在`egenshin`下的`gacha`里的`__init__.py`第`15`行的`name='原神抽卡',  # 功能名` 改成 `name='原神抽卡2',  # 功能名`

**Comment by liuqianpan2008** [comment]
确实√ 感谢
