### ISSUE TITLE
大佬，能不能新加一个判断

### ISSUE THREAD

**Issue by GinNide** [pcrbot/erinilis-modules#5]
例如 
大家说111回答222
发送“111”，机器人回答了“222”
但是发送“我想说111”，机器人不会回答
因为我是开发java的，python的语法和Java有点出入，想自己改但是有心无力

我的想法是 将获取到消息（str1）与设置的问题（str2）做比较 如果消息这个字符串包含了我设置的字符串 （str1 in str2）那么我就return回答。
嗯 就是这样 期待大佬的回答，如果能改的话大佬可以提交一份代码给我或者教我怎么改也行。QAQ see you

**Comment by GinNide** [comment]
已经star了

**Comment by yuyumoko** [comment]
> 例如
> 大家说111回答222
> 发送“111”，机器人回答了“222”
> 但是发送“我想说111”，机器人不会回答
> 因为我是开发java的，python的语法和Java有点出入，想自己改但是有心无力
> 
> 我的想法是 将获取到消息（str1）与设置的问题（str2）做比较 如果消息这个字符串包含了我设置的字符串 （str1 in str2）那么我就return回答。
> 嗯 就是这样 期待大佬的回答，如果能改的话大佬可以提交一份代码给我或者教我怎么改也行。QAQ see you

在135行处
# 回复的函数
async def answer(ctx):
    msg = util.get_message_str(ctx['message']).strip()
    ans_list = db.get(msg, [])

msg实际上就是拉取到的消息文字,  db就是问题的列表 key就是消息关键字,  实际上也可以看做 db[msg].
比如
{
 "111":[{...}],
 "222":[{...}]
}

真实的数据例如
{"?":[{"user_id": 389897773, "group_id": 723220XXX, "is_me": false, "qus": "?", "message": [{"type": "text", "data": {"text": "\u00bf"}}]}]}

你可以取出db中全部的key值做个 in 的对比 , 在进行下一步处理吧.

**Comment by GinNide** [comment]
感谢大佬回复我去看看代码

**Comment by GinNide** [comment]
> > 例如
> > 大家说111回答222
> > 发送“ 111”，机器人回答了“ 222”
> > 但是发送“我想说111”，机器人不会回答
> > 因为我是开发java的，python的语法和Java有点出入，想自己改但是有心无力
> > 我的想法是将获取到消息（str1）与设置的问题（str2）做比较如果消息这个字符串包含了我设置的字符串（str2 in str2）那么我就return回答。
> > 嗯就是这样期待大佬的回答，如果能改的话大佬可以提交一份代码给我或者教我怎么改也行。
> 
> 在135行处
> 
> # 回复的函数
> 异步定义答案（ctx）：
> msg = util.get_message_str（ctx ['message']）。strip（）
> ans_list = db.get（msg，[]）
> 
> MSG实际上就是拉取到的消息文字，分贝就是问题的列表键就是消息关键字，实际上也可以看做分贝[MSG]。
> 比如
> {
> “111”：[{...}]，
> “222” ：[{...}]
> }
> 
> 真实的数据例如
> {“？”：[{“ user_id”：389897773，“ group_id”：723220XXX，“ is_me”：false，“ qus”：“？”，“ message”：[{“ type”：“ text” ，“ data”：{“ text”：“ \ u00bf”}}]}]}}
> 
> 您可以取出db中全部的键值做个在的对比中，在进行后续处理吧。

### 我是这样理解的
`msg` 就是`真实数据`（一个`字典套列表`） 
ans_list  =  
`｛
    “111”：[{...}]，
    “222” ：[{...}]
 }`



｛｝里面就是拿到的真实数据 那么我要做的就是吧`type`这个键对应的值拿出来进行对比 如果 type：text 中有db这个字符串那就return 回答（小声bb在哪里进行返回回答）
