### ISSUE TITLE
原神插件报错

### ISSUE THREAD

**Issue by doubilbm** [pcrbot/erinilis-modules#52]
[error.log](https://github.com/pcrbot/erinilis-modules/files/7209423/error.log)
大佬请问这个报错是什么原因，已经解决了几个报错了但这个我是真不会了，救救

**Comment by yuyumoko** [comment]
如果你要使用原神成就功能的话 你需要到百度云那注册一下[OCR](https://cloud.baidu.com/product/ocr) 能免费领取额度的,
如果你不使用这个功能 就直接
```
  baidu_ocr:
    API_KEY: ******
    SECRET_KEY: ******
```
改成 , 即直接删除
```
  baidu_ocr:
    API_KEY: 
    SECRET_KEY: 
```

**Comment by yuyumoko** [comment]
[配置文件](https://github.com/pcrbot/erinilis-modules/blob/master/egenshin/config.yml#L44)里
