### ISSUE TITLE
原神卡池记录

### ISSUE THREAD

**Issue by DBlby** [pcrbot/erinilis-modules#53]
![20210923032055](https://user-images.githubusercontent.com/91221020/134408207-ddd63bf6-58e5-44e6-8387-70565230c9a6.jpg)
按照这个说明绑定一直提示“缺少必要参数(authkey)”确定没复制错，请问是什么问题呢

**Comment by yuyumoko** [comment]
这个报错是因为在链接中找不到authkey参数, 比如
&game_version=CNRELWin2.1.0_R4379056_S4398912_D4398912&`authkey=knJJAZo0`
你确认一下 你发送的消息接收到的有这个参数  , 在bot的控制台那边确认

**Comment by doubilbm** [comment]
![20210923033825](https://user-images.githubusercontent.com/62131661/134410489-de1454c3-a211-4e1e-8fdc-aa07546189e2.jpg)
这个应该算是接收到了吧

**Comment by yuyumoko** [comment]
咦, 要不你来我群测试一下吧 723220342
