### ISSUE TITLE
egenshin原神插件 成就无法查询

### ISSUE THREAD

**Issue by YouKnowMyEggs** [pcrbot/erinilis-modules#54]
配置好百度OCR API，使用截图更新成就时，后台没有任何报错，机器人也提示正在更新成就，但是查看缺少成就时总提示记录的成就太少，在百度查询API调用次数时，显示为0。

**Comment by yuyumoko** [comment]
更新成就时, 有没有提示识别了多少 比如

本次识别结果增加了146个记录 过程:图片顺序(识别到的成就个数)
1(7) 2(7) 3(7) 4(7) 5(7) 6(7) 7(7) 8(7) 9(6) 10(7) 11(9) 12(7) 13(6) 14(7) 15(8) 16(8) 17(7) 18(8) 19(7) 20(7) 21(8) 22(2)

**Comment by YouKnowMyEggs** [comment]
> 更新成就时, 有没有提示识别了多少 比如
> 
> 本次识别结果增加了146个记录 过程:图片顺序(识别到的成就个数)
> 1(7) 2(7) 3(7) 4(7) 5(7) 6(7) 7(7) 8(7) 9(6) 10(7) 11(9) 12(7) 13(6) 14(7) 15(8) 16(8) 17(7) 18(8) 19(7) 20(7) 21(8) 22(2)

感谢，刚刚提醒了，是我太没耐心了，他反应了1个多小时...
