### ISSUE TITLE
大佬，关于原神猜语音，有点小建议

### ISSUE THREAD

**Issue by a970703218** [pcrbot/erinilis-modules#63]
能否获取简短的那种语音，增加难度性呢？现在获取的这些语音，都是二十多秒的长语音，很容易就被群友猜出来了【跪谢】

**Comment by a970703218** [comment]
> 这

【太厚脸皮了很抱歉！】就是他们觉得，太简单了【无奈】

**Comment by yuyumoko** [comment]
来 试试就逝逝

**Comment by yuyumoko** [comment]
新的命令是 原神猜语音2

**Comment by a970703218** [comment]
> 新的命令是 原神猜语音2

哇！已更新，感谢大佬爷青回₍ᐢ⸝⸝› ̫ ‹⸝⸝ᐢ₎
