### ISSUE TITLE
大佬，那个便笺怎么用啊

### ISSUE THREAD

**Issue by a970703218** [pcrbot/erinilis-modules#66]
我到浏览器去取，浏览器没弹出代码
![Uploading Screenshot_20211017_113215_com.microsoft.rdc.androidx.jpg…]()

**Comment by yuyumoko** [comment]
试试这个
`javascript:(()=>{_=(name)=>{for(i in(r=document.cookie.split("; "))){arr=r[i].split("=");if(arr[0]==name)return arr[1]}};alert(_("account_id")+","+_("cookie_token"))})();`

**Comment by a970703218** [comment]
> 试试这个 `javascript:(()=>{_=(name)=>{for(i in(r=document.cookie.split("; "))){arr=r[i].split("=");if(arr[0]==name)return arr[1]}};alert(_("account_id")+","+_("cookie_token"))})();`

还是不行ε=ε=(っ*´□`)っ
![Screenshot_20211017_123953_com microsoft rdc androidx](https://user-images.githubusercontent.com/48351858/137611700-cb141ac3-4442-4ea1-947c-ef7f1a8cfb3a.jpg)

**Comment by yuyumoko** [comment]
```
javascript: (() =>  {
  _ = (name) => {
    for (i in (r = document.cookie.split("; "))) {
      var arr = r[i].split("=");
      if (arr[0] == name) return arr[1];
    }
  };
  alert(_("account_id") + "," + _("cookie_token"));
})();
```
这个呢

**Comment by yuyumoko** [comment]
不是 ,, 我看你执行的代码好奇怪啊

**Comment by a970703218** [comment]
> ```
> javascript: (() =>  {
>   _ = (name) => {
>     for (i in (r = document.cookie.split("; "))) {
>       var arr = r[i].split("=");
>       if (arr[0] == name) return arr[1];
>     }
>   };
>   alert(_("account_id") + "," + _("cookie_token"));
> })();
> ```
> 
> 这个呢

都

> 不是 ,, 我看你执行的代码好奇怪啊

我是直接复制粘贴的，这样不行的吗ヽ(ﾟДﾟ)ﾉ
![Uploading Screenshot_20211017_124309_com.microsoft.rdc.androidx.jpg…]()

**Comment by yuyumoko** [comment]
```
javascript:(()=>{_=(name)=>{for(i in(r=document.cookie.split("; "))){arr=r[i].split("=");if(arr[0]==name)return arr[1]}};alert(_("account_id")+","+_("cookie_token"))})();
```

你确定的复制这个吗 再试试

**Comment by a970703218** [comment]
> ```
> javascript:(()=>{_=(name)=>{for(i in(r=document.cookie.split("; "))){arr=r[i].split("=");if(arr[0]==name)return arr[1]}};alert(_("account_id")+","+_("cookie_token"))})();
> ```
> 
> 你确定的复制这个吗 再试试

是复制的这个，我用的傲游浏览器，是这个的问题吗(=ﾟДﾟ=)

**Comment by yuyumoko** [comment]
你试一下chrome , 或者把他添加到收藏 然后直接在米游社打开也是可以的

**Comment by a970703218** [comment]
> 你试一下chrome , 或者把他添加到收藏 然后直接在米游社打开也是可以的

还是这样子∑(O_O；)感觉我的智商不太够了٩(´Д` ;)۶:.*
![Screenshot_20211017_125240_com microsoft rdc androidx](https://user-images.githubusercontent.com/48351858/137612069-564baeab-1de5-46f0-ad2e-bdcb98143f2b.jpg)

**Comment by yuyumoko** [comment]
.. 为什么你的断开来了 那就试试没格式化前的
```
javascript: (() =>  {
  _ = (name) => {
    for (i in (r = document.cookie.split("; "))) {
      var arr = r[i].split("=");
      if (arr[0] == name) return arr[1];
    }
  };
  alert(_("account_id") + "," + _("cookie_token"));
})();
```

**Comment by a970703218** [comment]
> .. 为什么你的断开来了 那就试试没格式化前的
> 
> ```
> javascript: (() =>  {
>   _ = (name) => {
>     for (i in (r = document.cookie.split("; "))) {
>       var arr = r[i].split("=");
>       if (arr[0] == name) return arr[1];
>     }
>   };
>   alert(_("account_id") + "," + _("cookie_token"));
> })();
> ```

一回车他就运行了-`д´-

**Comment by yuyumoko** [comment]
> > .. 为什么你的断开来了 那就试试没格式化前的
> > ```
> > javascript: (() =>  {
> >   _ = (name) => {
> >     for (i in (r = document.cookie.split("; "))) {
> >       var arr = r[i].split("=");
> >       if (arr[0] == name) return arr[1];
> >     }
> >   };
> >   alert(_("account_id") + "," + _("cookie_token"));
> > })();
> > ```
> 
> 一回车他就运行了-`д´-

啊?  所以成功了吗

**Comment by a970703218** [comment]
> > > .. 为什么你的断开来了 那就试试没格式化前的
> > > ```
> > > javascript: (() =>  {
> > >   _ = (name) => {
> > >     for (i in (r = document.cookie.split("; "))) {
> > >       var arr = r[i].split("=");
> > >       if (arr[0] == name) return arr[1];
> > >     }
> > >   };
> > >   alert(_("account_id") + "," + _("cookie_token"));
> > > })();
> > > ```
> > 
> > 
> > 一回车他就运行了-`д´-
> 
> 啊? 所以成功了吗

然后控制台弹这个，没回应δ(´д｀; )不知道算不算成功
![Screenshot_20211017_130321_com microsoft rdc androidx](https://user-images.githubusercontent.com/48351858/137612392-4cab5525-4916-4eb5-98a6-8498129cc490.jpg)

**Comment by yuyumoko** [comment]
升级hoshino到最新版本

**Comment by a970703218** [comment]
> 你暴露token了 我帮你删了消息了

好的，谢谢大佬。»ू(͒ˑ•᷄͡ꇵ͒•᷅͒)ू?!

**Comment by a970703218** [comment]
> 升级hoshino到最新版本

好的ヾ ^_^♪

**Comment by a970703218** [comment]
> 你暴露token了 我帮你删了消息了

大佬 我按照网页弹出的那个复制进去，然后他提示cookies信息错误∑(O_O；)
