### ISSUE TITLE
大佬，关于原神抽卡解析那个

### ISSUE THREAD

**Issue by Juenia** [pcrbot/erinilis-modules#69]
![Screenshot_20211021_181807_com microsoft rdc androidx](https://user-images.githubusercontent.com/48351858/138258747-73db2a28-7268-440a-ad9d-1d18bd1cf376.jpg)
这个是啥问题啊，那个网站我用宝塔搭建的，打开是空白的，是我搭建错了吗？ヽ(ﾟДﾟ)ﾉ

**Comment by yuyumoko** [comment]
报错最后是啥
