### ISSUE TITLE
epixiv登录失败

### ISSUE THREAD

**Issue by yzkoori** [pcrbot/erinilis-modules#7]
开启bot后在加载epixiv时提示“登录失败，请检查配置”
试过两个px号，问题一样，在web和rsshub里登录是正常的

**Comment by yuyumoko** [comment]
https://github.com/upbit/pixivpy/issues/158 暂时只能先等等修复了

**Comment by noahzark** [comment]
自制的pixiv也挂了 Orz

看原issue有这么一个[solution](https://github.com/upbit/pixivpy/issues/158#issuecomment-777815440)，准备先用refresh token顶上了 2333

**Comment by noahzark** [comment]
快进到用nb实现oauth2 client，然后注册一个接口来接收refresh token（写好发我
