### ISSUE TITLE
大佬，关于gacha的error

### ISSUE THREAD

**Issue by a970703218** [pcrbot/erinilis-modules#79]
![Screenshot_20211101_170204_com microsoft rdc androidx](https://user-images.githubusercontent.com/48351858/139647802-75aa2995-c043-4960-9150-f37ed03aaebf.jpg)
这个是什么错误啊，好像从上一个尘世之锁就有了

**Comment by yuyumoko** [comment]
啊这 , 武器名字 我写错了

**Comment by a970703218** [comment]
> 啊这 , 武器名字 我写错了
原来是这样呀【挠头】诶嘿
