### ISSUE TITLE
大佬，原神uid查询好像出问题了

### ISSUE THREAD

**Issue by a970703218** [pcrbot/erinilis-modules#80]
![Screenshot_20211101_193527_com tencent mobileqq](https://user-images.githubusercontent.com/48351858/139665719-2b104d11-5fd4-4e72-a253-8b3a8f8ee5fa.jpg)
全都变成这样了ヽ(ﾟДﾟ)ﾉ，无论哪个id都是

**Comment by yuyumoko** [comment]
你上米游社看看还有吗

**Comment by a970703218** [comment]
> 你上米游社看看还有吗

米游社提示接口异常

**Comment by yuyumoko** [comment]
> > 你上米游社看看还有吗
> 
> 米游社提示接口异常

那就等会吧

**Comment by a970703218** [comment]
> > > 你上米游社看看还有吗
> > 
> > 
> > 米游社提示接口异常
> 
> 那就等会吧

好哒(*ﾟ∀ﾟ*)
