### ISSUE TITLE
关于epixiv的问题

### ISSUE THREAD

**Issue by as6296463** [pcrbot/erinilis-modules#81]
按照流程获取到refresh_token后改了config.yml文件，然后能搜到图但是发不出来，求大佬帮忙，搞了一早上和一下午没整好。
![QQ截图20211102155337](https://user-images.githubusercontent.com/37761817/139807537-b33e1c17-9449-4269-8cc5-1d8a83f49f36.png)
![QQ截图20211102155516](https://user-images.githubusercontent.com/37761817/139807590-ad51c390-999e-414b-b4e6-85eb052c88ad.png)

**Comment by yuyumoko** [comment]
建议使用 [plugins-index](https://github.com/pcrbot/HoshinoBot-plugins-index) 其他的项目 这个我不打算维护了

**Comment by as6296463** [comment]
> 建议使用 [plugins-index](https://github.com/pcrbot/HoshinoBot-plugins-index) 其他的项目 这个我不打算维护了

已经弄好了，是配置文件的问题，short_url_enable默认是开着的，关了就好了
