### ISSUE TITLE
ERROR：找不到原神资料卡.png问题

### ISSUE THREAD

**Issue by drsxyh** [pcrbot/erinilis-modules#82]
开发者你好，启动Hoshino的过程中，遇到了一点问题，说找不到原神资料卡.png，求大佬帮忙看看，应该所有依赖都是安装好的。并且在群聊中公告功能可以正常使用的，唯有查询个人信息和便笺无法使用
![$0EVMMTH%HG)ZR6P@(Z65QV](https://user-images.githubusercontent.com/58547035/139860816-44ff294d-73c7-4997-97c7-0ff695084538.png)

**Comment by yuyumoko** [comment]
是linux吗

**Comment by yuyumoko** [comment]
你换个ssh客户端 这个是因为编码问题

**Comment by yuyumoko** [comment]
或者直接在linux上clone本项目

**Comment by drsxyh** [comment]
感谢，真是编码的问题，前面Linux下clone太慢了，我就在本地clone上传上去的，现在正常了
