### ISSUE TITLE
原神十连报错

### ISSUE THREAD

**Issue by Eternity-luo** [pcrbot/erinilis-modules#88]
不知道为什么报错😂
![3bed0fb41f4c7d7b](https://user-images.githubusercontent.com/72162184/143136895-8c8b2096-30d1-4391-83d9-079c680f7dc5.png)

**Comment by yuyumoko** [comment]
因为卡池关了

**Comment by Eternity-luo** [comment]
> 因为卡池关了

哦哦😂，刚部署没多久😂
