### ISSUE TITLE
现时很容易出现[visit too frequently]错误

### ISSUE THREAD

**Issue by Edvision** [pcrbot/erinilis-modules#91]
查询卡池进度时响应：
{'page': '2', 'size': '20', 'total': '0', 'list': [{'uid': '117092574', 'gacha_type': '301', 'item_id': '', 'count': '1', 'time': '2021-11-02 18:40:38', 'name': '胡桃', 'lang': 'zh-cn', 'item_type': '角色', 'rank_type': '5', 'i
d': '1635847560144880800'}, {'uid': '117092574', 'gacha_type': '301', 'item_id': '', 'count': '1', 'time': '2021-11-02 18:40:28', 'name': '神射手之誓', 'lang': 'zh-cn', 'item_type': '武器', 'rank_type': '3', 'id': '163584756014
4675070'}, {'uid': '117092574', 'gacha_type': '301', 'item_id': '', 'count': '1', 'time': '2021-11-02 18:40:28', 'name': '迪奥娜', 'lang': 'zh-cn', 'item_type': '角色', 'rank_type': '4', 'id': '1635847560144675069'}, {'uid': '1
17092574', 'gacha_type': '301', 'item_id': '', 'count': '1', 'time': '2021-11-02 18:40:28', 'name': '鸦羽弓', 'lang': 'zh-cn', 'item_type': '武器', 'rank_type': '3', 'id': '1635847560144675068'}, {'uid': '117092574', 'gacha_typ
e': '301', 'item_id': '', 'count': '1', 'time': '2021-11-02 18:40:28', 'name': '讨龙英杰谭', 'lang': 'zh-cn', 'item_type': '武器', 'rank_type': '3', 'id': '1635847560144675067'}, {'uid': '117092574', 'gacha_type': '301', 'item_
id': '', 'count': '1', 'time': '2021-11-02 18:40:28', 'name': '早柚', 'lang': 'zh-cn', 'item_type': '角色', 'rank_type': '4', 'id': '1635847560144675066'}, {'uid': '117092574', 'gacha_type': '301', 'item_id': '', 'count': '1', 
'time': '2021-11-02 18:40:28', 'name': '鸦羽弓', 'lang': 'zh-cn', 'item_type': '武器', 'rank_type': '3', 'id': '1635847560144675065'}, {'uid': '117092574', 'gacha_type': '301', 'item_id': '', 'count': '1', 'time': '2021-11-02 1
8:40:28', 'name': '弹弓', 'lang': 'zh-cn', 'item_type': '武器', 'rank_type': '3', 'id': '1635847560144675064'}, {'uid': '117092574', 'gacha_type': '301', 'item_id': '', 'count': '1', 'time': '2021-11-02 18:40:28', 'name': '神射
手之誓', 'lang': 'zh-cn', 'item_type': '武器', 'rank_type': '3', 'id': '1635847560144675063'}, {'uid': '117092574', 'gacha_type': '301', 'item_id': '', 'count': '1', 'time': '2021-11-02 18:40:28', 'name': '鸦羽弓', 'lang': 'zh-
cn', 'item_type': '武器', 'rank_type': '3', 'id': '1635847560144675062'}, {'uid': '117092574', 'gacha_type': '301', 'item_id': '', 'count': '1', 'time': '2021-11-02 18:40:28', 'name': '魔导绪论', 'lang': 'zh-cn', 'item_type': '
武器', 'rank_type': '3', 'id': '1635847560144675061'}, {'uid': '117092574', 'gacha_type': '301', 'item_id': '', 'count': '1', 'time': '2021-11-02 18:39:37', 'name': '翡玉法球', 'lang': 'zh-cn', 'item_type': '武器', 'rank_type':
 '3', 'id': '1635847560143599345'}, {'uid': '117092574', 'gacha_type': '301', 'item_id': '', 'count': '1', 'time': '2021-11-02 18:39:37', 'name': '早柚', 'lang': 'zh-cn', 'item_type': '角色', 'rank_type': '4', 'id': '1635847560
143599344'}, {'uid': '117092574', 'gacha_type': '301', 'item_id': '', 'count': '1', 'time': '2021-11-02 18:39:37', 'name': '弹弓', 'lang': 'zh-cn', 'item_type': '武器', 'rank_type': '3', 'id': '1635847560143599343'}, {'uid': '1
17092574', 'gacha_type': '301', 'item_id': '', 'count': '1', 'time': '2021-11-02 18:39:37', 'name': '以理服人', 'lang': 'zh-cn', 'item_type': '武器', 'rank_type': '3', 'id': '1635847560143599342'}, {'uid': '117092574', 'gacha_t
ype': '301', 'item_id': '', 'count': '1', 'time': '2021-11-02 18:39:37', 'name': '神射手之誓', 'lang': 'zh-cn', 'item_type': '武器', 'rank_type': '3', 'id': '1635847560143599341'}, {'uid': '117092574', 'gacha_type': '301', 'ite
m_id': '', 'count': '1', 'time': '2021-11-02 18:39:37', 'name': '托马', 'lang': 'zh-cn', 'item_type': '角色', 'rank_type': '4', 'id': '1635847560143599340'}, {'uid': '117092574', 'gacha_type': '301', 'item_id': '', 'count': '1'
, 'time': '2021-11-02 18:39:37', 'name': '弹弓', 'lang': 'zh-cn', 'item_type': '武器', 'rank_type': '3', 'id': '1635847560143599339'}, {'uid': '117092574', 'gacha_type': '301', 'item_id': '', 'count': '1', 'time': '2021-11-02 1
8:39:37', 'name': '弹弓', 'lang': 'zh-cn', 'item_type': '武器', 'rank_type': '3', 'id': '1635847560143599338'}, {'uid': '117092574', 'gacha_type': '301', 'item_id': '', 'count': '1', 'time': '2021-11-02 18:39:37', 'name': '以理
服人', 'lang': 'zh-cn', 'item_type': '武器', 'rank_type': '3', 'id': '1635847560143599337'}], 'region': 'cn_gf01'}

{'retcode': 0, 'message': 'OK', 'data': {'page': '1', 'size': '20', 'total': '0', 'list': [{'uid': '117092574', 'gacha_type': '301', 'item_id': '', 'count': '1', 'time': '2021-11-20 00:44:32', 'name': '沐浴龙血的剑', 'lang': 'z
h-cn', 'item_type': '武器', 'rank_type': '3', 'id': '1637337960000884683'}, {'uid': '117092574', 'gacha_type': '301', 'item_id': '', 'count': '1', 'time': '2021-11-20 00:44:32', 'name': '早柚', 'lang': 'zh-cn', 'item_type': '角
色', 'rank_type': '4', 'id': '1637337960000884682'}, {'uid': '117092574', 'gacha_type': '301', 'item_id': '', 'count': '1', 'time': '2021-11-20 00:44:32', 'name': '托马', 'lang': 'zh-cn', 'item_type': '角色', 'rank_type': '4', 
'id': '1637337960000884681'}, {'uid': '117092574', 'gacha_type': '301', 'item_id': '', 'count': '1', 'time': '2021-11-20 00:44:32', 'name': '以理服人', 'lang': 'zh-cn', 'item_type': '武器', 'rank_type': '3', 'id': '163733796000
0884680'}, {'uid': '117092574', 'gacha_type': '301', 'item_id': '', 'count': '1', 'time': '2021-11-20 00:44:32', 'name': '黎明神剑', 'lang': 'zh-cn', 'item_type': '武器', 'rank_type': '3', 'id': '1637337960000884679'}, {'uid': 
'117092574', 'gacha_type': '301', 'item_id': '', 'count': '1', 'time': '2021-11-20 00:44:32', 'name': '弹弓', 'lang': 'zh-cn', 'item_type': '武器', 'rank_type': '3', 'id': '1637337960000884678'}, {'uid': '117092574', 'gacha_typ
e': '301', 'item_id': '', 'count': '1', 'time': '2021-11-20 00:44:32', 'name': '以理服人', 'lang': 'zh-cn', 'item_type': '武器', 'rank_type': '3', 'id': '1637337960000884677'}, {'uid': '117092574', 'gacha_type': '301', 'item_id
': '', 'count': '1', 'time': '2021-11-20 00:44:32', 'name': '飞天御剑', 'lang': 'zh-cn', 'item_type': '武器', 'rank_type': '3', 'id': '1637337960000884676'}, {'uid': '117092574', 'gacha_type': '301', 'item_id': '', 'count': '1'
, 'time': '2021-11-20 00:44:32', 'name': '神射手之誓', 'lang': 'zh-cn', 'item_type': '武器', 'rank_type': '3', 'id': '1637337960000884675'}, {'uid': '117092574', 'gacha_type': '301', 'item_id': '', 'count': '1', 'time': '2021-1
1-20 00:44:32', 'name': '黑缨枪', 'lang': 'zh-cn', 'item_type': '武器', 'rank_type': '3', 'id': '1637337960000884674'}, {'uid': '117092574', 'gacha_type': '301', 'item_id': '', 'count': '1', 'time': '2021-11-07 23:15:53', 'name
': '黎明神剑', 'lang': 'zh-cn', 'item_type': '武器', 'rank_type': '3', 'id': '1636297560000444358'}, {'uid': '117092574', 'gacha_type': '301', 'item_id': '', 'count': '1', 'time': '2021-11-07 23:15:53', 'name': '以理服人', 'lan
g': 'zh-cn', 'item_type': '武器', 'rank_type': '3', 'id': '1636297560000444357'}, {'uid': '117092574', 'gacha_type': '301', 'item_id': '', 'count': '1', 'time': '2021-11-07 23:15:53', 'name': '迪奥娜', 'lang': 'zh-cn', 'item_ty
pe': '角色', 'rank_type': '4', 'id': '1636297560000444356'}, {'uid': '117092574', 'gacha_type': '301', 'item_id': '', 'count': '1', 'time': '2021-11-07 23:15:53', 'name': '黑缨枪', 'lang': 'zh-cn', 'item_type': '武器', 'rank_ty
pe': '3', 'id': '1636297560000444355'}, {'uid': '117092574', 'gacha_type': '301', 'item_id': '', 'count': '1', 'time': '2021-11-07 23:15:53', 'name': '以理服人', 'lang': 'zh-cn', 'item_type': '武器', 'rank_type': '3', 'id': '16
36297560000444354'}, {'uid': '117092574', 'gacha_type': '301', 'item_id': '', 'count': '1', 'time': '2021-11-07 23:15:53', 'name': '沐浴龙血的剑', 'lang': 'zh-cn', 'item_type': '武器', 'rank_type': '3', 'id': '16362975600004443
53'}, {'uid': '117092574', 'gacha_type': '301', 'item_id': '', 'count': '1', 'time': '2021-11-07 23:15:53', 'name': '神射手之誓', 'lang': 'zh-cn', 'item_type': '武器', 'rank_type': '3', 'id': '1636297560000444352'}, {'uid': '11
7092574', 'gacha_type': '301', 'item_id': '', 'count': '1', 'time': '2021-11-07 23:15:53', 'name': '魔导绪论', 'lang': 'zh-cn', 'item_type': '武器', 'rank_type': '3', 'id': '1636297560000444351'}, {'uid': '117092574', 'gacha_ty
pe': '301', 'item_id': '', 'count': '1', 'time': '2021-11-07 23:15:53', 'name': '黑缨枪', 'lang': 'zh-cn', 'item_type': '武器', 'rank_type': '3', 'id': '1636297560000444350'}, {'uid': '117092574', 'gacha_type': '301', 'item_id'
: '', 'count': '1', 'time': '2021-11-07 23:15:53', 'name': '神射手之誓', 'lang': 'zh-cn', 'item_type': '武器', 'rank_type': '3', 'id': '1636297560000444349'}], 'region': 'cn_gf01'}}

{'retcode': 0, 'message': 'OK', 'data': {'page': '1', 'size': '20', 'total': '0', 'list': [], 'region': 'cn_gf01'}}

{'data': None, 'message': 'visit too frequently', 'retcode': -110}

尝试在gacha_log.py的get_logs中加入sleep，减少了些问题发生的概率
for page in range(1, 9999):
            if add_history:
                break
            if end_id == -1:
                break
            time.sleep(0.3)
            clist = (await self.get_api(page=page, gacha_type=gacha_type, end_id=end_id)).list or (req_history and history)

**Comment by yuyumoko** [comment]
切换卡池时会这样 0.3可以吗 我设置的是1秒

**Comment by Edvision** [comment]
> 
好的，谢谢。可以的。有修复就行。我昨天才拿代码下来跑，发现跑不通

**Comment by yuyumoko** [comment]
他才刚刚更新的机制 之前没有的
