### ISSUE TITLE
ysa#查询不知道为什么显示不全

### ISSUE THREAD

**Issue by Eternity-luo** [pcrbot/erinilis-modules#92]
![Screenshot_2021-11-25-17-46-28-737_com tencent mobileqq](https://user-images.githubusercontent.com/72162184/143418325-1da96ae8-9792-4dc2-9122-f27b63d62e6d.jpg)
![1f4ff01ff3dac966](https://user-images.githubusercontent.com/72162184/143418332-c2972c91-bb8d-407c-a542-4a6e61007f07.jpg)

**Comment by yuyumoko** [comment]
现在米游社只能查询别人8个人物, 你绑定一下yss 查询自己就是全的

**Comment by Eternity-luo** [comment]
> 现在米游社只能查询别人8个人物, 你绑定一下yss 查询自己就是全的

已经绑定过了，查询还是显示不全
![Screenshot_2021-11-25-17-58-15-040_com tencent mobileqq](https://user-images.githubusercontent.com/72162184/143420182-47fa2161-c04f-4441-8c3f-ee0222f8ab43.jpg)

**Comment by yuyumoko** [comment]
有缓存 内置半小时 不然你可以重启

**Comment by yuyumoko** [comment]
这个是米游社今天更新的机制

**Comment by Eternity-luo** [comment]
> 这个是米游社今天更新的机制

清除yss绑定的文件在哪，我想试试重新绑定行不行

> 这个是米游社今天更新的机制

嗯，我重新获取一下ck绑定，等半个小时再试试😂

**Comment by yuyumoko** [comment]
> > 这个是米游社今天更新的机制
> 
> 清除yss绑定的文件在哪，我想试试重新绑定行不行
> 
> > 这个是米游社今天更新的机制
> 
> 嗯，我重新获取一下ck绑定，等半个小时再试试😂

不用删文件啊.. 你就直接绑定就行 都是替换的  而且缓存重启一下bot就行
