### ISSUE TITLE
pixiv

### ISSUE THREAD

**Issue by zhouy005x** [pcrbot/erinilis-modules#96]
![-73da7eaf856b85f0](https://user-images.githubusercontent.com/64981486/143607939-c564b9ae-7a96-4455-9f86-fa5167422877.png)
这个是哪里错了😂

**Comment by zhouy005x** [comment]
![Uploading -727870f89bbe62f3.png…]()

**Comment by yuyumoko** [comment]
他免翻墙访问支持出问题了.. 我还不知道用啥

**Comment by zhouy005x** [comment]
> 他免翻墙访问支持出问题了.. 我还不知道用啥

哦哦，谢谢
