### ISSUE TITLE
关于添加令牌和yss绑定之后出现的问题

### ISSUE THREAD

**Issue by isteve123** [pcrbot/erinilis-modules#97]
![7MEDC$O Q_562C)@Z2E%09E](https://user-images.githubusercontent.com/76209149/144585482-0aacb82e-b621-4dfa-966c-c18e95856566.png)

**Comment by isteve123** [comment]
依赖正常，config.yml修改了，cookie填上去了

**Comment by yuyumoko** [comment]
你这个是hoshino版本太低 是私聊问题
